version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./SimpleAuthSpringBackend
      dockerfile: Dockerfile
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      SECRET_KEY: $SECRET_KEY
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./simple_auth-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: